project:
  type: book
  execute-dir: project

execute:
  freeze: auto

filters:
  - naquiz

book:
  title: "WEHI R Course"
  author: "Shian Su & Kathleen Zeglinski"
  date: today
  favicon: "favicon.ico"
  sidebar:
    search: true
    title: "WEHI R Course Book"
    style: docked
    logo: "WEHI_RGB_logo.png"
  chapters:
    - index.qmd
    - setup.qmd
    - chapter_1.qmd
    - chapter_2.qmd
    - chapter_3.qmd
    - chapter_4.qmd
    - chapter_5.qmd
    - chapter_6.qmd
    - further_reading.qmd
    #- advanced_topics.qmd

bibliography: references.bib
csl: vancouver_superscript.csl
format:
  html:
    grid:
      body-width: 1000px
      margin-width: 20px
      sidebar-width: 300px
    theme: litera_edited.scss
    code-fold: false
    fig-width: 10
    fig-height: 5
    fig-dpi: 200
    code-summary: "Show code"
    code-tools:
      source: true
      toggle: false
      caption: none
    code-overflow: wrap
    highlight-style: textmate.theme
    number-sections: true
